name:                HsProof
version:             0.1.0.0
github:              "Meowcolm024/HsProof"
license:             BSD3
author:              "Malcolm Law"
maintainer:          ":)"
copyright:           "Malcolm Law"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Meowcolm024/HsProof#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2 && < 3
- transformers >= 0.5.6.2 && < 6
- lens >= 5 && < 6

library:
  source-dirs: src

executables:
  HsProof-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HsProof

tests:
  HsProof-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HsProof
